// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: dya/oled_status/oled_status.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "dya.oled_status";

export enum Orientation {
  ORIENTATION_LANDSCAPE = 0,
  ORIENTATION_PORTRAIT = 1,
  UNRECOGNIZED = -1,
}

export function orientationFromJSON(object: any): Orientation {
  switch (object) {
    case 0:
    case "ORIENTATION_LANDSCAPE":
      return Orientation.ORIENTATION_LANDSCAPE;
    case 1:
    case "ORIENTATION_PORTRAIT":
      return Orientation.ORIENTATION_PORTRAIT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Orientation.UNRECOGNIZED;
  }
}

export function orientationToJSON(object: Orientation): string {
  switch (object) {
    case Orientation.ORIENTATION_LANDSCAPE:
      return "ORIENTATION_LANDSCAPE";
    case Orientation.ORIENTATION_PORTRAIT:
      return "ORIENTATION_PORTRAIT";
    case Orientation.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Animation {
  ANIMATION_OFF = 0,
  ANIMATION_CYBER_FACE = 1,
  UNRECOGNIZED = -1,
}

export function animationFromJSON(object: any): Animation {
  switch (object) {
    case 0:
    case "ANIMATION_OFF":
      return Animation.ANIMATION_OFF;
    case 1:
    case "ANIMATION_CYBER_FACE":
      return Animation.ANIMATION_CYBER_FACE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Animation.UNRECOGNIZED;
  }
}

export function animationToJSON(object: Animation): string {
  switch (object) {
    case Animation.ANIMATION_OFF:
      return "ANIMATION_OFF";
    case Animation.ANIMATION_CYBER_FACE:
      return "ANIMATION_CYBER_FACE";
    case Animation.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface OledStatusConfig {
  orientation: Orientation;
  showCentralBattery: boolean;
  showPeripheralBatteries: boolean;
  showOutput: boolean;
  showLayer: boolean;
  showWpm: boolean;
  showModifiers: boolean;
  showHidIndicators: boolean;
  animation: Animation;
}

export interface Capabilities {
  centralBattery: boolean;
  peripheralBatteries: boolean;
  output: boolean;
  layer: boolean;
  wpm: boolean;
  modifiers: boolean;
  hidIndicators: boolean;
  portrait: boolean;
  landscape: boolean;
  animationCyberFace: boolean;
}

export interface GetConfigRequest {
}

export interface GetConfigResponse {
  config?: OledStatusConfig | undefined;
  capabilities?: Capabilities | undefined;
}

export interface SetConfigRequest {
  config?: OledStatusConfig | undefined;
}

export interface SetConfigResponse {
  config?: OledStatusConfig | undefined;
}

export interface ResetConfigRequest {
}

export interface ResetConfigResponse {
  config?: OledStatusConfig | undefined;
}

export interface ErrorResponse {
  message: string;
}

export interface Request {
  getConfig?: GetConfigRequest | undefined;
  setConfig?: SetConfigRequest | undefined;
  resetConfig?: ResetConfigRequest | undefined;
}

export interface Response {
  error?: ErrorResponse | undefined;
  getConfig?: GetConfigResponse | undefined;
  setConfig?: SetConfigResponse | undefined;
  resetConfig?: ResetConfigResponse | undefined;
}

function createBaseOledStatusConfig(): OledStatusConfig {
  return {
    orientation: 0,
    showCentralBattery: false,
    showPeripheralBatteries: false,
    showOutput: false,
    showLayer: false,
    showWpm: false,
    showModifiers: false,
    showHidIndicators: false,
    animation: 0,
  };
}

export const OledStatusConfig: MessageFns<OledStatusConfig> = {
  encode(message: OledStatusConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orientation !== 0) {
      writer.uint32(8).int32(message.orientation);
    }
    if (message.showCentralBattery !== false) {
      writer.uint32(16).bool(message.showCentralBattery);
    }
    if (message.showPeripheralBatteries !== false) {
      writer.uint32(24).bool(message.showPeripheralBatteries);
    }
    if (message.showOutput !== false) {
      writer.uint32(32).bool(message.showOutput);
    }
    if (message.showLayer !== false) {
      writer.uint32(40).bool(message.showLayer);
    }
    if (message.showWpm !== false) {
      writer.uint32(48).bool(message.showWpm);
    }
    if (message.showModifiers !== false) {
      writer.uint32(56).bool(message.showModifiers);
    }
    if (message.showHidIndicators !== false) {
      writer.uint32(64).bool(message.showHidIndicators);
    }
    if (message.animation !== 0) {
      writer.uint32(72).int32(message.animation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OledStatusConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOledStatusConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.orientation = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.showCentralBattery = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.showPeripheralBatteries = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.showOutput = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.showLayer = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.showWpm = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.showModifiers = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.showHidIndicators = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.animation = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OledStatusConfig {
    return {
      orientation: isSet(object.orientation) ? orientationFromJSON(object.orientation) : 0,
      showCentralBattery: isSet(object.showCentralBattery)
        ? globalThis.Boolean(object.showCentralBattery)
        : isSet(object.show_central_battery)
        ? globalThis.Boolean(object.show_central_battery)
        : false,
      showPeripheralBatteries: isSet(object.showPeripheralBatteries)
        ? globalThis.Boolean(object.showPeripheralBatteries)
        : isSet(object.show_peripheral_batteries)
        ? globalThis.Boolean(object.show_peripheral_batteries)
        : false,
      showOutput: isSet(object.showOutput)
        ? globalThis.Boolean(object.showOutput)
        : isSet(object.show_output)
        ? globalThis.Boolean(object.show_output)
        : false,
      showLayer: isSet(object.showLayer)
        ? globalThis.Boolean(object.showLayer)
        : isSet(object.show_layer)
        ? globalThis.Boolean(object.show_layer)
        : false,
      showWpm: isSet(object.showWpm)
        ? globalThis.Boolean(object.showWpm)
        : isSet(object.show_wpm)
        ? globalThis.Boolean(object.show_wpm)
        : false,
      showModifiers: isSet(object.showModifiers)
        ? globalThis.Boolean(object.showModifiers)
        : isSet(object.show_modifiers)
        ? globalThis.Boolean(object.show_modifiers)
        : false,
      showHidIndicators: isSet(object.showHidIndicators)
        ? globalThis.Boolean(object.showHidIndicators)
        : isSet(object.show_hid_indicators)
        ? globalThis.Boolean(object.show_hid_indicators)
        : false,
      animation: isSet(object.animation) ? animationFromJSON(object.animation) : 0,
    };
  },

  toJSON(message: OledStatusConfig): unknown {
    const obj: any = {};
    if (message.orientation !== 0) {
      obj.orientation = orientationToJSON(message.orientation);
    }
    if (message.showCentralBattery !== false) {
      obj.showCentralBattery = message.showCentralBattery;
    }
    if (message.showPeripheralBatteries !== false) {
      obj.showPeripheralBatteries = message.showPeripheralBatteries;
    }
    if (message.showOutput !== false) {
      obj.showOutput = message.showOutput;
    }
    if (message.showLayer !== false) {
      obj.showLayer = message.showLayer;
    }
    if (message.showWpm !== false) {
      obj.showWpm = message.showWpm;
    }
    if (message.showModifiers !== false) {
      obj.showModifiers = message.showModifiers;
    }
    if (message.showHidIndicators !== false) {
      obj.showHidIndicators = message.showHidIndicators;
    }
    if (message.animation !== 0) {
      obj.animation = animationToJSON(message.animation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OledStatusConfig>, I>>(base?: I): OledStatusConfig {
    return OledStatusConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OledStatusConfig>, I>>(object: I): OledStatusConfig {
    const message = createBaseOledStatusConfig();
    message.orientation = object.orientation ?? 0;
    message.showCentralBattery = object.showCentralBattery ?? false;
    message.showPeripheralBatteries = object.showPeripheralBatteries ?? false;
    message.showOutput = object.showOutput ?? false;
    message.showLayer = object.showLayer ?? false;
    message.showWpm = object.showWpm ?? false;
    message.showModifiers = object.showModifiers ?? false;
    message.showHidIndicators = object.showHidIndicators ?? false;
    message.animation = object.animation ?? 0;
    return message;
  },
};

function createBaseCapabilities(): Capabilities {
  return {
    centralBattery: false,
    peripheralBatteries: false,
    output: false,
    layer: false,
    wpm: false,
    modifiers: false,
    hidIndicators: false,
    portrait: false,
    landscape: false,
    animationCyberFace: false,
  };
}

export const Capabilities: MessageFns<Capabilities> = {
  encode(message: Capabilities, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.centralBattery !== false) {
      writer.uint32(8).bool(message.centralBattery);
    }
    if (message.peripheralBatteries !== false) {
      writer.uint32(16).bool(message.peripheralBatteries);
    }
    if (message.output !== false) {
      writer.uint32(24).bool(message.output);
    }
    if (message.layer !== false) {
      writer.uint32(32).bool(message.layer);
    }
    if (message.wpm !== false) {
      writer.uint32(40).bool(message.wpm);
    }
    if (message.modifiers !== false) {
      writer.uint32(48).bool(message.modifiers);
    }
    if (message.hidIndicators !== false) {
      writer.uint32(56).bool(message.hidIndicators);
    }
    if (message.portrait !== false) {
      writer.uint32(64).bool(message.portrait);
    }
    if (message.landscape !== false) {
      writer.uint32(72).bool(message.landscape);
    }
    if (message.animationCyberFace !== false) {
      writer.uint32(80).bool(message.animationCyberFace);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Capabilities {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCapabilities();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.centralBattery = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.peripheralBatteries = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.output = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.layer = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.wpm = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.modifiers = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.hidIndicators = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.portrait = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.landscape = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.animationCyberFace = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Capabilities {
    return {
      centralBattery: isSet(object.centralBattery)
        ? globalThis.Boolean(object.centralBattery)
        : isSet(object.central_battery)
        ? globalThis.Boolean(object.central_battery)
        : false,
      peripheralBatteries: isSet(object.peripheralBatteries)
        ? globalThis.Boolean(object.peripheralBatteries)
        : isSet(object.peripheral_batteries)
        ? globalThis.Boolean(object.peripheral_batteries)
        : false,
      output: isSet(object.output) ? globalThis.Boolean(object.output) : false,
      layer: isSet(object.layer) ? globalThis.Boolean(object.layer) : false,
      wpm: isSet(object.wpm) ? globalThis.Boolean(object.wpm) : false,
      modifiers: isSet(object.modifiers) ? globalThis.Boolean(object.modifiers) : false,
      hidIndicators: isSet(object.hidIndicators)
        ? globalThis.Boolean(object.hidIndicators)
        : isSet(object.hid_indicators)
        ? globalThis.Boolean(object.hid_indicators)
        : false,
      portrait: isSet(object.portrait) ? globalThis.Boolean(object.portrait) : false,
      landscape: isSet(object.landscape) ? globalThis.Boolean(object.landscape) : false,
      animationCyberFace: isSet(object.animationCyberFace)
        ? globalThis.Boolean(object.animationCyberFace)
        : isSet(object.animation_cyber_face)
        ? globalThis.Boolean(object.animation_cyber_face)
        : false,
    };
  },

  toJSON(message: Capabilities): unknown {
    const obj: any = {};
    if (message.centralBattery !== false) {
      obj.centralBattery = message.centralBattery;
    }
    if (message.peripheralBatteries !== false) {
      obj.peripheralBatteries = message.peripheralBatteries;
    }
    if (message.output !== false) {
      obj.output = message.output;
    }
    if (message.layer !== false) {
      obj.layer = message.layer;
    }
    if (message.wpm !== false) {
      obj.wpm = message.wpm;
    }
    if (message.modifiers !== false) {
      obj.modifiers = message.modifiers;
    }
    if (message.hidIndicators !== false) {
      obj.hidIndicators = message.hidIndicators;
    }
    if (message.portrait !== false) {
      obj.portrait = message.portrait;
    }
    if (message.landscape !== false) {
      obj.landscape = message.landscape;
    }
    if (message.animationCyberFace !== false) {
      obj.animationCyberFace = message.animationCyberFace;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Capabilities>, I>>(base?: I): Capabilities {
    return Capabilities.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Capabilities>, I>>(object: I): Capabilities {
    const message = createBaseCapabilities();
    message.centralBattery = object.centralBattery ?? false;
    message.peripheralBatteries = object.peripheralBatteries ?? false;
    message.output = object.output ?? false;
    message.layer = object.layer ?? false;
    message.wpm = object.wpm ?? false;
    message.modifiers = object.modifiers ?? false;
    message.hidIndicators = object.hidIndicators ?? false;
    message.portrait = object.portrait ?? false;
    message.landscape = object.landscape ?? false;
    message.animationCyberFace = object.animationCyberFace ?? false;
    return message;
  },
};

function createBaseGetConfigRequest(): GetConfigRequest {
  return {};
}

export const GetConfigRequest: MessageFns<GetConfigRequest> = {
  encode(_: GetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetConfigRequest {
    return {};
  },

  toJSON(_: GetConfigRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetConfigRequest>, I>>(base?: I): GetConfigRequest {
    return GetConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetConfigRequest>, I>>(_: I): GetConfigRequest {
    const message = createBaseGetConfigRequest();
    return message;
  },
};

function createBaseGetConfigResponse(): GetConfigResponse {
  return { config: undefined, capabilities: undefined };
}

export const GetConfigResponse: MessageFns<GetConfigResponse> = {
  encode(message: GetConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      OledStatusConfig.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.capabilities !== undefined) {
      Capabilities.encode(message.capabilities, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = OledStatusConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.capabilities = Capabilities.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetConfigResponse {
    return {
      config: isSet(object.config) ? OledStatusConfig.fromJSON(object.config) : undefined,
      capabilities: isSet(object.capabilities) ? Capabilities.fromJSON(object.capabilities) : undefined,
    };
  },

  toJSON(message: GetConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = OledStatusConfig.toJSON(message.config);
    }
    if (message.capabilities !== undefined) {
      obj.capabilities = Capabilities.toJSON(message.capabilities);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetConfigResponse>, I>>(base?: I): GetConfigResponse {
    return GetConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetConfigResponse>, I>>(object: I): GetConfigResponse {
    const message = createBaseGetConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? OledStatusConfig.fromPartial(object.config)
      : undefined;
    message.capabilities = (object.capabilities !== undefined && object.capabilities !== null)
      ? Capabilities.fromPartial(object.capabilities)
      : undefined;
    return message;
  },
};

function createBaseSetConfigRequest(): SetConfigRequest {
  return { config: undefined };
}

export const SetConfigRequest: MessageFns<SetConfigRequest> = {
  encode(message: SetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      OledStatusConfig.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = OledStatusConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetConfigRequest {
    return { config: isSet(object.config) ? OledStatusConfig.fromJSON(object.config) : undefined };
  },

  toJSON(message: SetConfigRequest): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = OledStatusConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetConfigRequest>, I>>(base?: I): SetConfigRequest {
    return SetConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetConfigRequest>, I>>(object: I): SetConfigRequest {
    const message = createBaseSetConfigRequest();
    message.config = (object.config !== undefined && object.config !== null)
      ? OledStatusConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseSetConfigResponse(): SetConfigResponse {
  return { config: undefined };
}

export const SetConfigResponse: MessageFns<SetConfigResponse> = {
  encode(message: SetConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      OledStatusConfig.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = OledStatusConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SetConfigResponse {
    return { config: isSet(object.config) ? OledStatusConfig.fromJSON(object.config) : undefined };
  },

  toJSON(message: SetConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = OledStatusConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SetConfigResponse>, I>>(base?: I): SetConfigResponse {
    return SetConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SetConfigResponse>, I>>(object: I): SetConfigResponse {
    const message = createBaseSetConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? OledStatusConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseResetConfigRequest(): ResetConfigRequest {
  return {};
}

export const ResetConfigRequest: MessageFns<ResetConfigRequest> = {
  encode(_: ResetConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ResetConfigRequest {
    return {};
  },

  toJSON(_: ResetConfigRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ResetConfigRequest>, I>>(base?: I): ResetConfigRequest {
    return ResetConfigRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResetConfigRequest>, I>>(_: I): ResetConfigRequest {
    const message = createBaseResetConfigRequest();
    return message;
  },
};

function createBaseResetConfigResponse(): ResetConfigResponse {
  return { config: undefined };
}

export const ResetConfigResponse: MessageFns<ResetConfigResponse> = {
  encode(message: ResetConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      OledStatusConfig.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = OledStatusConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResetConfigResponse {
    return { config: isSet(object.config) ? OledStatusConfig.fromJSON(object.config) : undefined };
  },

  toJSON(message: ResetConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = OledStatusConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResetConfigResponse>, I>>(base?: I): ResetConfigResponse {
    return ResetConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResetConfigResponse>, I>>(object: I): ResetConfigResponse {
    const message = createBaseResetConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? OledStatusConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ErrorResponse {
    return { message: isSet(object.message) ? globalThis.String(object.message) : "" };
  },

  toJSON(message: ErrorResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ErrorResponse>, I>>(base?: I): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ErrorResponse>, I>>(object: I): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRequest(): Request {
  return { getConfig: undefined, setConfig: undefined, resetConfig: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getConfig !== undefined) {
      GetConfigRequest.encode(message.getConfig, writer.uint32(10).fork()).join();
    }
    if (message.setConfig !== undefined) {
      SetConfigRequest.encode(message.setConfig, writer.uint32(18).fork()).join();
    }
    if (message.resetConfig !== undefined) {
      ResetConfigRequest.encode(message.resetConfig, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getConfig = GetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.setConfig = SetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.resetConfig = ResetConfigRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Request {
    return {
      getConfig: isSet(object.getConfig)
        ? GetConfigRequest.fromJSON(object.getConfig)
        : isSet(object.get_config)
        ? GetConfigRequest.fromJSON(object.get_config)
        : undefined,
      setConfig: isSet(object.setConfig)
        ? SetConfigRequest.fromJSON(object.setConfig)
        : isSet(object.set_config)
        ? SetConfigRequest.fromJSON(object.set_config)
        : undefined,
      resetConfig: isSet(object.resetConfig)
        ? ResetConfigRequest.fromJSON(object.resetConfig)
        : isSet(object.reset_config)
        ? ResetConfigRequest.fromJSON(object.reset_config)
        : undefined,
    };
  },

  toJSON(message: Request): unknown {
    const obj: any = {};
    if (message.getConfig !== undefined) {
      obj.getConfig = GetConfigRequest.toJSON(message.getConfig);
    }
    if (message.setConfig !== undefined) {
      obj.setConfig = SetConfigRequest.toJSON(message.setConfig);
    }
    if (message.resetConfig !== undefined) {
      obj.resetConfig = ResetConfigRequest.toJSON(message.resetConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Request>, I>>(base?: I): Request {
    return Request.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Request>, I>>(object: I): Request {
    const message = createBaseRequest();
    message.getConfig = (object.getConfig !== undefined && object.getConfig !== null)
      ? GetConfigRequest.fromPartial(object.getConfig)
      : undefined;
    message.setConfig = (object.setConfig !== undefined && object.setConfig !== null)
      ? SetConfigRequest.fromPartial(object.setConfig)
      : undefined;
    message.resetConfig = (object.resetConfig !== undefined && object.resetConfig !== null)
      ? ResetConfigRequest.fromPartial(object.resetConfig)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, getConfig: undefined, setConfig: undefined, resetConfig: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.getConfig !== undefined) {
      GetConfigResponse.encode(message.getConfig, writer.uint32(18).fork()).join();
    }
    if (message.setConfig !== undefined) {
      SetConfigResponse.encode(message.setConfig, writer.uint32(26).fork()).join();
    }
    if (message.resetConfig !== undefined) {
      ResetConfigResponse.encode(message.resetConfig, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getConfig = GetConfigResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setConfig = SetConfigResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.resetConfig = ResetConfigResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Response {
    return {
      error: isSet(object.error) ? ErrorResponse.fromJSON(object.error) : undefined,
      getConfig: isSet(object.getConfig)
        ? GetConfigResponse.fromJSON(object.getConfig)
        : isSet(object.get_config)
        ? GetConfigResponse.fromJSON(object.get_config)
        : undefined,
      setConfig: isSet(object.setConfig)
        ? SetConfigResponse.fromJSON(object.setConfig)
        : isSet(object.set_config)
        ? SetConfigResponse.fromJSON(object.set_config)
        : undefined,
      resetConfig: isSet(object.resetConfig)
        ? ResetConfigResponse.fromJSON(object.resetConfig)
        : isSet(object.reset_config)
        ? ResetConfigResponse.fromJSON(object.reset_config)
        : undefined,
    };
  },

  toJSON(message: Response): unknown {
    const obj: any = {};
    if (message.error !== undefined) {
      obj.error = ErrorResponse.toJSON(message.error);
    }
    if (message.getConfig !== undefined) {
      obj.getConfig = GetConfigResponse.toJSON(message.getConfig);
    }
    if (message.setConfig !== undefined) {
      obj.setConfig = SetConfigResponse.toJSON(message.setConfig);
    }
    if (message.resetConfig !== undefined) {
      obj.resetConfig = ResetConfigResponse.toJSON(message.resetConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Response>, I>>(base?: I): Response {
    return Response.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Response>, I>>(object: I): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.getConfig = (object.getConfig !== undefined && object.getConfig !== null)
      ? GetConfigResponse.fromPartial(object.getConfig)
      : undefined;
    message.setConfig = (object.setConfig !== undefined && object.setConfig !== null)
      ? SetConfigResponse.fromPartial(object.setConfig)
      : undefined;
    message.resetConfig = (object.resetConfig !== undefined && object.resetConfig !== null)
      ? ResetConfigResponse.fromPartial(object.resetConfig)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
